### ISSUE TITLE
Forgelin crash

### ISSUE THREAD

**Issue by diamondstars** [shadowfacts/Forgelin#61]
Upon starting MC the game crashes. Can someone give me a solution?

crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.211.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 7/10/19 12:30 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Moving World (movingworld)
Caused by: java.lang.NullPointerException
	at com.elytradev.movingworld.common.config.priority.AssemblePriorityConfig.discoverPoweredBlocks(AssemblePriorityConfig.java:168)
	at com.elytradev.movingworld.common.config.priority.AssemblePriorityConfig.loadAndSaveInit(AssemblePriorityConfig.java:87)
	at com.elytradev.movingworld.MovingWorldMod.init(MovingWorldMod.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 792591912 bytes (755 MB) / 1912602624 bytes (1824 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                           | Version           | Source                                        | Signature                                |
	|:----- |:-------------------------------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft                                    | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCHI  | mcp                                          | 9.42              | minecraft.jar                                 | None                                     |
	| UCHI  | FML                                          | 8.0.99.99         | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                                        | 14.23.5.2768      | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | micdoodlecore                                |                   | minecraft.jar                                 | None                                     |
	| UCHI  | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                                 | None                                     |
	| UCHI  | forgelin                                     | 1.8.3             | Forgelin-1.8.3.jar                            | None                                     |
	| UCHI  | betterportals                                | 0.1.6             | betterportals-0.1.6.jar                       | None                                     |
	| UCHI  | buildcraftlib                                | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
	| UCHI  | buildcraftcore                               | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
	| UCHI  | buildcraftbuilders                           | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
	| UCHI  | buildcrafttransport                          | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
	| UCHI  | buildcraftsilicon                            | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
	| UCHI  | buildcraftcompat                             | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
	| UCHI  | buildcraftenergy                             | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
	| UCHI  | buildcraftfactory                            | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
	| UCHI  | buildcraftrobotics                           | 7.99.24.1         | buildcraft-all-7.99.24.1.jar                  | None                                     |
	| UCHI  | codechickenlib                               | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHEE | movingworld                                  | 1.12-6.342        | movingworld-1.12-6.342-full.jar               | None                                     |
	| UCH   | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar           | None                                     |
	| UCH   | mantle                                       | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| UCH   | jei                                          | 4.15.0.268        | jei_1.12.2-4.15.0.268.jar                     | None                                     |
	| UCH   | tconstruct                                   | 1.12.2-2.12.0.157 | TConstruct-1.12.2-2.12.0.157.jar              | None                                     |
	| UCH   | galacticraftcore                             | 4.0.2.211         | GalacticraftCore-1.12.2-4.0.2.211.jar         | None                                     |
	| UCH   | galacticraftplanets                          | 4.0.2.211         | Galacticraft-Planets-1.12.2-4.0.2.211.jar     | None                                     |
	| UCH   | waila                                        | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| UCH   | nei                                          | 2.4.2             | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | xaerominimap                                 | 1.17.3            | Xaeros_Minimap_1.17.3_Forge_1.12.jar          | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.211.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
	GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-10.36.19' Renderer: 'Intel HD Graphics 5000 OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

**Comment by SkullBonez2** [comment]
"| UCH**EE** | movingworld "

This is a Davinci's Vessels issue, as its coremod (movingworld) is the only thing that has errored.

**Comment by diamondstars** [comment]
Thanks
