### ISSUE TITLE
Minecraft crash on startup 1.12.2 forge. asking for help

### ISSUE THREAD

**Issue by RCVision** [shadowfacts/Forgelin#75]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.30_mc1.12.2.jar)
  CamPatchingLoader (CMDCam_v1.4.10_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CreativePatchingLoader (CreativeCore_v1.10.20_mc1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
Contact their authors BEFORE contacting forge

Time: 10/22/21 6:43 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LittleTiles (littletiles)
Caused by: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/config/premade/Permission
	at com.creativemd.littletiles.LittleTilesConfig.<init>(LittleTilesConfig.java:29)
	at com.creativemd.littletiles.LittleTiles.PreInit(LittleTiles.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.common.config.premade.Permission
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 801964568 bytes (764 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version               | Source                                  | Signature                                |
	|:----- |:----------------- |:--------------------- |:--------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2                | minecraft.jar                           | None                                     |
	| LCH   | mcp               | 9.42                  | minecraft.jar                           | None                                     |
	| LCH   | FML               | 8.0.99.99             | forge-1.12.2-14.23.5.2855.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2855          | forge-1.12.2-14.23.5.2855.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy | 1.0.0                 | minecraft.jar                           | None                                     |
	| LCH   | littletilescore   | 1.0.0                 | minecraft.jar                           | None                                     |
	| LCH   | securitycraft     | v1.8.19.3             | [1.12.2]+SecurityCraft+v1.8.19.3.jar    | None                                     |
	| LCH   | creativecore      | 1.10.0                | CreativeCore_v1.10.20_mc1.12.2.jar      | None                                     |
	| LCE   | littletiles       | 1.5.0                 | LittleTiles_v1.5.30_mc1.12.2.jar        | None                                     |
	| LC    | alet              | 1.0                   | A+Little+Extra+Tiles-1.0.22a.jar        | None                                     |
	| LC    | architecturecraft | @VERSION@             | architecturecraft-1.12-3.98.jar         | None                                     |
	| LC    | bibliocraft       | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar       | None                                     |
	| LC    | ctm               | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar               | None                                     |
	| LC    | chisel            | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar            | None                                     |
	| LC    | cmdcam            | 1.4.0                 | CMDCam_v1.4.10_mc1.12.2.jar             | None                                     |
	| LC    | customnpcs        | 1.12                  | CustomNPCs_1.12.2-(05Jul20).jar         | None                                     |
	| LC    | ptrmodellib       | 1.0.4                 | PTRLib-1.0.4.jar                        | None                                     |
	| LC    | props             | 2.6.0                 | Decocraft-2.6.0_1.12.2.jar              | None                                     |
	| LC    | forgelin          | 1.8.2                 | Forgelin-1.8.2.jar                      | None                                     |
	| LC    | cfm               | 6.3.1                 | furniture-6.3.1-1.12.2.jar              | None                                     |
	| LC    | kirosblocks       | 1.1                   | kirosblocks-1.1.jar                     | None                                     |
	| LC    | littleopener      | 1.0.1                 | littleopener-1.0.1.jar                  | None                                     |
	| LC    | malisiscore       | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar            | None                                     |
	| LC    | malisisdoors      | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar           | None                                     |
	| LC    | malisisswitches   | 1.12.2-5.1.0          | malisisswitches-1.12.2-5.1.0.jar        | None                                     |
	| LC    | moreplayermodels  | 1.12.2                | MorePlayerModels_1.12.2-(05Dec19).jar   | None                                     |
	| LC    | opframe           | 1.4.0                 | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar | None                                     |
	| LC    | variedcommodities | 1.12.2                | VariedCommodities_1.12.2(21nov19).jar   | None                                     |
	| LC    | llibrary          | 1.7.19                | llibrary-1.7.19-1.12.2.jar              | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LittlePatchingLoader (LittleTiles_v1.5.30_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CamPatchingLoader (CMDCam_v1.4.10_mc1.12.2.jar)
  com.creativemd.cmdcam.transform.CamTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.20_mc1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14739 Compatibility Profile Context 21.6.1 27.20.22001.14011' Renderer: 'Radeon RX 570 Series'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14739 Compatibility Profile Context 21.6.1 27.20.22001.14011
	OpenGlRenderer: Radeon RX 570 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by brandonsay95** [comment]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LittleTiles (littletiles)
| LCE   | littletiles       | 1.5.0                 | LittleTiles_v1.5.30_mc1.12.2.jar        | None                                     |
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

Loaded,Constructed,Errored
